Refactor Gradle and Dockerfile for reuse

diff --git a/gradle-plugins/src/main/resources/docker/Dockerfile-python b/gradle-plugins/src/main/resources/docker/Dockerfile-python
--- a/gradle-plugins/src/main/resources/docker/Dockerfile-python
+++ b/gradle-plugins/src/main/resources/docker/Dockerfile-python
@@ -6,22 +6,9 @@ ARG BASE_IMAGE="python:3.10-alpine"
 FROM ${BASE_IMAGE}
 
 # hadolint ignore=DL3018
-RUN apk update && apk --no-cache upgrade && apk add git && rm -rf /var/cache/apk/*
-
-RUN adduser --disabled-password tron
-
-ARG HEALTHCHECK_PORT_ARG
-ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
-ARG HEALTHCHECK_CMD_ARG="curl --fail http://localhost:${HEALTHCHECK_PORT}/health || exit 1"
-ENV HEALTHCHECK_CMD=${HEALTHCHECK_CMD_ARG}
-HEALTHCHECK CMD eval $HEALTHCHECK_CMD
+RUN apk update && apk --no-cache upgrade && apk add git curl && rm -rf /var/cache/apk/*
 
 WORKDIR /app
-ARG ENTRYPOINT_FILE=entrypoint.sh
-# Workaround to copy ENTRYPOINT_FILE that may not exist
-# https://stackoverflow.com/a/46801962
-# Copy script that runs entrypoint.sh if it exists
-COPY set-env-secrets.src entrypoint-wrapper.sh ${ENTRYPOINT_FILE}* ./
 
 # Used to specify the service folder you want to build if running locally
 # No longer write *.pyc files to disk
@@ -29,16 +16,30 @@ ENV PYTHONDONTWRITEBYTECODE 1
 # Send logs directly to container
 ENV PYTHONUNBUFFERED 1
 
-# === Image layers above this line are general and will be reused as cache when building the image.
-# Put commands that produce project-specific image layers below this line.
-
-# Copy over all files specified in local.python.container-service-convention
-COPY . ./
-# install python packages, using a long timeout so that builds won't fail when the repo is slow (pypi.org)
+# Copy and install requirements first (without application code)
+# b/c this is a big image layer that doesn't change often
+# See https://vsupalov.com/5-tips-to-speed-up-docker-build/
+COPY requirements.txt ./
+# Install python packages using a long timeout so that builds won't fail when pypi.org is slow
 RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt
 
+ARG ENTRYPOINT_FILE=entrypoint.sh
+# Workaround to copy ENTRYPOINT_FILE that may not exist
+# https://stackoverflow.com/a/46801962
+# Copy script that runs entrypoint.sh if it exists
+COPY set-env-secrets.src entrypoint-wrapper.sh ${ENTRYPOINT_FILE}* ./
+
+# Copy application code, which changes more often,
+# along with files specified in local.python.container-service-convention
+COPY . ./
+
+RUN adduser --disabled-password tron
 RUN chmod +x ./*.sh && chown -R tron /app
 USER tron
-# The exec form of the Dockerfile ENTRYPOINT is used so that there is no shell wrapping the Java process.
-# The advantage is that the java process responds to KILL signals sent to the container.
 ENTRYPOINT ["/app/entrypoint-wrapper.sh"]
+
+ARG HEALTHCHECK_PORT_ARG
+ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
+ARG HEALTHCHECK_CMD_ARG="curl --fail http://localhost:${HEALTHCHECK_PORT}/health || exit 1"
+ENV HEALTHCHECK_CMD=${HEALTHCHECK_CMD_ARG}
+HEALTHCHECK CMD eval $HEALTHCHECK_CMD
diff --git a/svc-bgs-api/src/docker/Dockerfile b/svc-bgs-api/src/docker/Dockerfile
--- a/svc-bgs-api/src/docker/Dockerfile
+++ b/svc-bgs-api/src/docker/Dockerfile
@@ -6,32 +6,36 @@ FROM ruby:2.7.8-alpine3.16
 # hadolint ignore=DL3018
 RUN apk update && apk upgrade && apk --no-cache add git ruby-dev=3.1.4-r0 curl-dev build-base=0.5-r3 openssl && rm -rf /var/cache/apk/*
 
-RUN adduser --disabled-password --gecos "" tron
-
-ARG HEALTHCHECK_PORT_ARG=8080
-ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
-# TODO: add healthcheck for Ruby microservice
-# HEALTHCHECK CMD curl --fail http://localhost:${HEALTHCHECK_PORT}/actuator/health || exit 1
-
 WORKDIR /app
+
+# Copy and install Gems first (without application code)
+# b/c this is a big layer that doesn't change often
+# See https://vsupalov.com/5-tips-to-speed-up-docker-build/
+COPY Gemfile Gemfile.lock ./
+
+# After install, delete packages only needed during bundler install & clean APK cache
+RUN gem install bundler:2.4.10 --no-document && bundle install \
+    && gem update cgi \
+    && apk del git ruby-dev curl-dev build-base \
+    && rm -rf /var/cache/apk/*
+
 ARG ENTRYPOINT_FILE=entrypoint.sh
 # Workaround to copy ENTRYPOINT_FILE that may not exist
 # https://stackoverflow.com/a/46801962
 # Copy script that runs entrypoint.sh if it exists
 COPY set-env-secrets.src entrypoint-wrapper.sh ${ENTRYPOINT_FILE}* ./
 
-# TODO once application is stable, update Gemfile.lock with contents from image
-# and change next line to: COPY Gemfile Gemfile.lock ./
-COPY Gemfile Gemfile.lock ./
-
-# After install, delete packages only needed during bundler install & clean APK cache
-RUN gem install bundler:2.4.10 --no-document && bundle install && gem update cgi && apk del git ruby-dev curl-dev build-base && rm -rf /var/cache/apk/*
-
 # === Image layers above this line are general and will be reused as cache when building the image.
 # Put commands that produce project-specific image layers below this line.
 
+RUN adduser --disabled-password --gecos "" tron
 COPY . .
 RUN chmod +x ./*.sh && chown -R tron /app
 
 USER tron
 ENTRYPOINT ["/app/entrypoint-wrapper.sh"]
+
+ARG HEALTHCHECK_PORT_ARG=8080
+ENV HEALTHCHECK_PORT=${HEALTHCHECK_PORT_ARG}
+# TODO: add healthcheck for Ruby microservice
+# HEALTHCHECK CMD curl --fail http://localhost:${HEALTHCHECK_PORT}/actuator/health || exit 1
