Mock BIE Kafka: add SSL authentication (#1877)
* tried pem
* jks works
* integration-test works
* no-ssl alternative
* tidy BieKafkaApplicationTest
* tidy Dockerfile
* update bie-kafka-end2end-test.yml
* don't use GitHub Action secrets
* add instructions

diff --git a/.github/workflows/bie-kafka-end2end-test.yml b/.github/workflows/bie-kafka-end2end-test.yml
--- a/.github/workflows/bie-kafka-end2end-test.yml
+++ b/.github/workflows/bie-kafka-end2end-test.yml
@@ -12,9 +12,6 @@ concurrency:
 
 env:
   COMPOSE_PROFILES: 'kafka'
-  TEST_TOPIC: 'TST_CONTENTION_BIE_CONTENTION_ASSOCIATED_TO_CLAIM_V02'
-  # TEST_DATA should be replaced with data after event_details is populated with non PII data. See Github Issue 1680
-  TEST_DATA: 'Lorem ipsum'
   VRO_DEV_SECRETS_FOLDER: "${{ github.workspace }}/.cache/abd-vro-dev-secrets"
 
 jobs:
@@ -82,7 +79,7 @@ jobs:
       - name: 'Wait for Kafka to be ready'
         run: |
           # Verify broker is up
-          BROKER_QUERY=$(kafkacat -m 30 -b localhost:9094 -L)
+          BROKER_QUERY=$(kafkacat -m 30 -b localhost:9092 -L)
           if echo $BROKER_QUERY | grep -q '1 brokers'
           then
             echo "Found Broker: $BROKER_QUERY"
@@ -112,13 +109,14 @@ jobs:
 
       - name: 'Create Kafka topic and send message'
         run: |
-          # Create Test File:
-          echo '${{env.TEST_DATA}}' > test.txt
-          echo "Producing message from test.txt on ${{env.TEST_TOPIC}}: "
-          cat test.txt
+          source scripts/setenv.sh
 
-          # Create Topic and Produce message on test topic
-          kafkacat -b localhost:9094 -P -t '${{env.TEST_TOPIC}}' -l test.txt
+          pushd svc-bie-kafka && { source ./docker-entryprep.sh; popd; }
+          if ! ./gradlew :svc-bie-kafka:integrationTest; then
+            echo "First run could fail due to some mock Kafka initialization"
+            # Subsequent runs should pass
+            ./gradlew :svc-bie-kafka:integrationTest
+          fi
 
       - name: 'Sleep to give time for message to travel end to end from kafka to saved in database'
         run: sleep 5
@@ -138,8 +136,6 @@ jobs:
             FROM
               claims.bie_contention_event
             WHERE
-              event='${{env.TEST_TOPIC}}'
-                AND
               event_details='Lorem ipsum'
           ")
           echo $RESULTS
