909: testing deploy notifications workflow

diff --git a/.github/workflows/deploy-unsigned.yml b/.github/workflows/deploy-unsigned.yml
--- a/.github/workflows/deploy-unsigned.yml
+++ b/.github/workflows/deploy-unsigned.yml
@@ -63,13 +63,12 @@ jobs:
       # https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1671643846200589?thread_ts=1671481495.084579&cid=C03UA9MV1EH
 
       - name: "Build, test, and publish ${{ env.TARGET_ENV }} images to GHCR"
-        # TODO: failing for now
-#        uses: ./.github/actions/publish-images
-#        with:
-#          target_env: ${{ env.TARGET_ENV }}
-#          access_token: ${{ secrets.ACCESS_TOKEN }}
-#          ghcr_username: ${{ github.actor }}
-#          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
+        uses: ./.github/actions/publish-images
+        with:
+          target_env: ${{ env.TARGET_ENV }}
+          access_token: ${{ secrets.ACCESS_TOKEN }}
+          ghcr_username: ${{ github.actor }}
+          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
         run: |
           exit 1
 
@@ -121,7 +120,9 @@ jobs:
           GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           GITHUB_USERNAME: ${{ secrets.USERNAME }}
         run: |
-          ./scripts/deploy-app.sh ${{ env.TARGET_ENV }} ${COMMIT_SHA:0:7}
+#          ./scripts/deploy-app.sh ${{ env.TARGET_ENV }} ${COMMIT_SHA:0:7}
+          # TODO: Fail for now
+          exit 1
 
       - name: "Wait for LHDI deployment"
         run: |
