909: testing deploy notifications workflow

diff --git a/.github/workflows/deploy-unsigned.yml b/.github/workflows/deploy-unsigned.yml
--- a/.github/workflows/deploy-unsigned.yml
+++ b/.github/workflows/deploy-unsigned.yml
@@ -35,6 +35,7 @@ jobs:
     if: github.repository == 'department-of-veterans-affairs/abd-vro'
     outputs:
       slack-response-ts: ${{ steps.slack-thread-id.outputs.slack_thread_ts }}
+      cancelled_job: ${{ steps.cancelled-job.outputs.cancelled-job }}
     runs-on: ubuntu-latest
     steps:
       - name: "Notify Slack"
@@ -62,12 +63,15 @@ jobs:
       # https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1671643846200589?thread_ts=1671481495.084579&cid=C03UA9MV1EH
 
       - name: "Build, test, and publish ${{ env.TARGET_ENV }} images to GHCR"
-        uses: ./.github/actions/publish-images
-        with:
-          target_env: ${{ env.TARGET_ENV }}
-          access_token: ${{ secrets.ACCESS_TOKEN }}
-          ghcr_username: ${{ github.actor }}
-          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
+        # TODO: failing for now
+#        uses: ./.github/actions/publish-images
+#        with:
+#          target_env: ${{ env.TARGET_ENV }}
+#          access_token: ${{ secrets.ACCESS_TOKEN }}
+#          ghcr_username: ${{ github.actor }}
+#          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          exit 1
 
       - name: "Cleanup ${{ env.TARGET_ENV }} images locally"
         run: |
@@ -81,9 +85,17 @@ jobs:
                        "ghcr.io/${{ github.repository }}/${IMG_NAME}:latest"
           done
 
+      - name: "Cancelled Deploy Images Job"
+        id: cancelled-job
+        if: cancelled()
+        run: |
+          echo "cancelled_job=${{ true }}" >> $GITHUB_OUTPUT
+
   deploy-images:
     needs: publish-images
     runs-on: ubuntu-latest
+    outputs:
+      cancelled_job: ${{ steps.cancelled-job.outputs.cancelled-job }}
     steps:
       - name: "Notify Slack: Deploying..."
         id: notify-slack-deploying
@@ -121,12 +133,26 @@ jobs:
             exit 1
           fi
 
-      - name: "Cancelled workflow"
+      - name: "Cancelled Deploy Images Job"
+        id: cancelled-job
         if: cancelled()
+        run: |
+          echo "cancelled_job=${{ true }}" >> $GITHUB_OUTPUT      
+
+  notify-slack:
+    needs: [publish-images, deploy-images]
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - name: "Cancelled jobs"
+        if: ${{ needs.publish-images.outputs.cancelled_job || needs.deploy-images.outputs.cancelled_job}}
         run: |
           echo 'DEPLOY_STATE_TEXT=:panda_blank: Deployment cancelled!' >> $GITHUB_ENV
           echo 'DEPLOY_STATE_EMOJI=black_square_for_stop' >> $GITHUB_ENV
 
+      # if either of the deploy jobs fail,
+      # the DEPLOY_STATE_TEXT and DEPLOY_STATE_EMOJI should not change from its default "failure" state
+      # and the message should be sent out as such
       - name: "Notify Slack: Thread deployment status"
         if: always()
         uses: archive/github-actions-slack@v2.6.0
