testing failure - explicit set of failed

diff --git a/.github/workflows/secrel.yml b/.github/workflows/secrel.yml
--- a/.github/workflows/secrel.yml
+++ b/.github/workflows/secrel.yml
@@ -39,8 +39,9 @@ jobs:
       - name: run secrel
 #    uses: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/.github/workflows/pipeline.yml@v3.2.0
 #        uses: actions/checkout@v3
-        run: exit 1 #0 is success, 1+ is failed
-#    with:
+        run: |
+          echo "JOB_STATUS=failed" >> $GITHUB_ENV
+          exit 1
 #      config-file: .github/secrel/config.yml
       - name: set job status
         id: job-status
