testing failure - change output: value

diff --git a/.github/workflows/secrel.yml b/.github/workflows/secrel.yml
--- a/.github/workflows/secrel.yml
+++ b/.github/workflows/secrel.yml
@@ -32,19 +32,17 @@ jobs:
     name: Tornado Pipeline
     runs-on: ubuntu-latest
     outputs:
-      job_status: ${{ steps.job-status.outputs.job_status }}
+      job_status: ${{ env.JOB_STATUS }}
 #    secrets: inherit
 
     steps:
       - name: run secrel
 #    uses: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/.github/workflows/pipeline.yml@v3.2.0
 #        uses: actions/checkout@v3
-        run: |
-          echo "JOB_STATUS=failed" >> $GITHUB_ENV
-          exit 1
+        run: exit 1
+#          echo "JOB_STATUS=failed" >> $GITHUB_ENV
 #      config-file: .github/secrel/config.yml
       - name: set job status
-        id: job-status
         run: echo "JOB_STATUS=success" >> $GITHUB_ENV
 
   notify-secrel-error:
@@ -57,7 +55,9 @@ jobs:
         uses: hmarr/debug-action@v2
 
       - name: otherdebug
-        run: echo ${{ needs.build-and-scan.outputs.job_status }}
+        run: |
+          echo ${{ needs.build-and-scan.outputs.job_status }}
+          echo "JOB_STATUS: $JOB_STATUS"
 
       - name: "Notify Slack on SecRel Failure"
         id: notify-slack
